insert into question  values(1,'What monitor type you want?')
insert into question  values(2,'What screen type you want?')
insert into question values(3,'What screen type you want?')
insert into question values(4,'What screen type you want?')
insert into question values(5,'What screen size you want?')
insert into question  values(6,'What monitor size you want?')
insert into question values(7,'What monitor size you want?')
insert into question values(8,'What monitor size you want?')
insert into question values(9,'What monitor size you want?')



insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(1,2,'Press 1 for Modular','1',null,1)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(2,3,'Press 2 for Semi-Modular','2',null,1)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(3,4,'Press 3 for Pre-Configured','3',null,1)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(4,5,'Press 1 for Touchscreen','1',null,2)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(5,6,'Press 2 for Non Touchscreen','2',null,2)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(6,7,'Press 1 for Touchscreen','1',null,3)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(7,8,'Press 2 for Non Touchscreen','2',null,3)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(8,9,'Press 1 for Touchscreen','1',null,4)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(9,0,'Press 1 for 9 inches','1','IntelliVue MX400',5)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(10,0,'Press 2 for 12 inches','2','IntelliVue MX450,IntelliVue MX500',5)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(11,0,'Press 3 for 15 inches','3','IntelliVue MX550',5)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(12,0,'Press 1 for 15 inches','1','IntelliVue MX600,IntelliVue MX700',6)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(13,0,'Press 2 for 19 inches','2','IntelliVue MX800',6)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(14,0,'Press 1 for 10 inches','1','Efficia CM10',7)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(15,0,'Press 2 for 12 inches','2','Efficia CM12',7)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(16,0,'Press 1 for 10 inches','1','Efficia CM100',8)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(17,0,'Press 2 for 12 inches','2','Efficia CM120',8)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(18,0,'Press 3 for 15 inches','3','Efficia CM150',8)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(19,0,'Press 1 for 10.4 inches','1','Goldway G30E',9)
insert into options(option_id,link_id,option_name,option_no,product_name,question_id) values(20,0,'Press 2 for 12.1 inches','2','Goldway G40E',9)
